### PR TITLE
Compile & run 5.4.0

### PR DESCRIPTION
**Pull request by carloslack**
Hey! I've been playing with ksocket and decided to update it to <= 5.4 kernels

- update to newer kernel_(connect/accept) API
- Fix a 5.4 crash when accept()
- Fix a couple more of minor issues
- Fix samples compilation by importing symvers

Here is a summary of it running using samples

    Tested on Linux ubuntu 5.4.0-66 x86-64
    
    [20651.173153] ksocket version 0.0.2
                   BSD-style socket APIs for kernel 5.0 developers
                   msn : song.xian-guang@hotmail.com
                   blog: http://sxg.cublog.cn
    [20666.927342] ksocket tcp srv init ok
    [20666.935602] sock_create sk= 0x00000000d1d8baad
    [20666.935606] sockfd_srv = 0x00000000d1d8baad
    [20666.935609] kbind ret = 0
    [20666.935611] family = 2, type = 1, protocol = 6
    [20675.506426] ksocket tcp cli init ok
    [20675.508137] sock_create sk= 0x000000005e2040e4
    [20675.508143] sockfd_cli = 0x000000005e2040e4
    [20675.508348] sockfd_cli = 0x000000005111d310
    [20675.508355] got connected from : 127.0.0.1 46064
    [20675.509777] connected to : quit 4444
    [20675.509833] got message : quit
    [20675.517874] got message : Hello, welcome to ksocket tcp srv service
    [20685.485744] ksocket tcp srv exit
    [20687.746083] ksocket tcp cli exit
    [20689.622516] ksocket exit

### CODE REVIEW

**Comment by hbagdi** [comment]
@carloslack Thanks for the patch.
I don't really have a way to test this patch anymore.
I'm thinking of the following solution:
- Create two branches, one for 5.4.0 and one for the old the code and keep both of them around
- Update README.md in the repo to describe the two branches
This way others can navigate and use the code as needed.
Thoughts?

**Comment by carloslack** [comment]
> @carloslack Thanks for the patch.
> I don't really have a way to test this patch anymore.
> I'm thinking of the following solution:
> 
> * Create two branches, one for 5.4.0 and one for the old the code and keep both of them around
> * Update README.md in the repo to describe the two branches
>   This way others can navigate and use the code as needed.
>   Thoughts?

Hey @hbagdi ! You're welcome

Your solution looks good to me, the other way around is also true, I haven't had much available time to test on 2.6 either.
If you create a 5.0 branch I will be happy to submit other PR's , if needed and over time, to keep that one up to date :)

It is also a good way to make sure the 2.6 version code, that's been around for a while, very stable.

**Comment by hbagdi** [comment]
>  If you create a 5.0 branch I will be happy to submit other PR's , if needed and over time, to keep that one up to date :)

I just created linux-5.4.0 branch.

Can you also send a PR to update the README.md file to point to relevant branches? Much appreciate your help here!

**Comment by carloslack** [comment]
> > If you create a 5.0 branch I will be happy to submit other PR's , if needed and over time, to keep that one up to date :)
> 
> I just created linux-5.4.0 branch.
> 
> Can you also send a PR to update the README.md file to point to relevant branches? Much appreciate your help here!

cool! Just a question, master will still be around right? what code it is going to have, 2.6 or 5.4? I ask so I know how to craft the README changes
Thanks!

**Comment by hbagdi** [comment]
> master will still be around right? what code it is going to have, 2.6 or 5.4? I ask so I know how to craft the README changes

Let's keep master as is, so 2.6.

**Pull request merged**
